# Spring Settings
spring.application.name=Form-Project003

spring.datasource.url=jdbc:postgresql://localhost:5432/camunda
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Atlas1616$$

spring.main.allow-circular-references=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

server.port=8080

# Camunda Settings
camunda.bpm.admin-user.id=user
camunda.bpm.admin-user.password=pass
camunda.bpm.auto-deployment-enabled=true
camunda.bpm.deployment-resource-pattern=classpath*:**/*.bpmn, classpath*:**/*.form,  classpath*:**/*.dmn, classpath*:**/*.cmmn
camunda.bpm.generic-properties.properties.historyTimeToLive=180
camunda.bpm.authorization.enabled=true
camunda.bpm.history-level=full
camunda.bpm.generic-properties.properties.authorizationEnabledForCustomCode=false
camunda.bpm.run.cors.enabled=true
camunda.bpm.run.cors.allowed-origins=http://localhost:3000
camunda.bpm.run.cors.enabled=true
camunda.bpm.run.cors.allowed-origins=http://localhost:5173